version: "3.8"

services:
  db:
    image: postgres:16.2
    container_name: agenda-db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      SSLMODE: true
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d/
    networks:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app
    depends_on:
      - db

networks:
  app: