version: "3.8"

services:
  db:
    image: postgres:16.2
    container_name: agenda-db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      SSLMODE: true
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app

networks:
  app: